/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXPWINDOW
#define ROOEXPWINDOW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExpWindow : public RooAbsPdf {
public:
  RooExpWindow() {} ; 
  RooExpWindow(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _alpha,
	      RooAbsReal& _imin);
  RooExpWindow(const RooExpWindow& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpWindow(*this,newname); }
  inline virtual ~RooExpWindow() { }

protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy imin ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExpWindow,1) // Your description goes here...
};
 
#endif
