/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooExpWindow.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooExpWindow) 

 RooExpWindow::RooExpWindow(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _alpha,
                        RooAbsReal& _imin) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   alpha("alpha","alpha",this,_alpha),
   imin("imin","imin",this,_imin)
 { 
 } 


 RooExpWindow::RooExpWindow(const RooExpWindow& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   alpha("alpha",this,other.alpha),
   imin("imin",this,other.imin)
 { 
 } 



 Double_t RooExpWindow::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
   double val =0.;
   double dmin = x- imin;
   if (dmin < 0) {
     val =0.;
   }
   else{
     val = exp(-alpha*dmin); 
   }
   return val;
 } 



